music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    # /music/
    path('', views.index, name='index'),
    #/music/:id/
    path('<album_id>/', views.detail, name='detail'),
    #/music/:id/favorite
    path('<album_id>/favorite', views.favorite, name='favorite'),
]

mydjangosite/urls.py
"""mydjangosite URL Configuration

The `urlpatterns` list routes URLs to templates. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function templates
    1. Add an import:  from my_app import templates
    2. Add a URL to urlpatterns:  path('', templates.home, name='home')
Class-based templates
    1. Add an import:  from other_app.templates import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return f'Album({self.artist}-{self.album_title}-{self.genre})'


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title

music/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template import loader

from music.models import Album, Song


# def index(req):
#     all_albums = Album.objects.all()
#     template = loader.get_template('music/index.html')
#     context = {
#         'all_albums': all_albums
#     }
#     return HttpResponse(template.render(context, req))

def index(req):
    all_albums = Album.objects.all()
    return render(req, 'music/index.html', {'all_albums': all_albums})


# def detail(req, album_id):
#     try:
#         album = Album.objects.get(id=album_id)
#     except Album.DoesNotExist:
#         raise Http404("Album does not exist")
#     return render(req, 'music/detail.html', {'album': album})

def detail(req, album_id):
    album = get_object_or_404(Album, id=album_id)
    return render(req, 'music/detail.html', {'album': album})


def favorite(req, album_id):
    album = get_object_or_404(Album, id=album_id)
    try:
        selected_song = album.song_set.get(id=req.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(req, 'music/detail.html', {
            'album': album,
            'error_message': "Not a valid song"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(req, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src="{{ album.album_logo }}" />

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist}}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<!--<ul>-->
    <!--{% for song in album.song_set.all %}-->
    <!--<li>{{ song.title }}</li>-->
    <!--{% endfor %}-->
<!--</ul>-->

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">{{ song.title }}
            {% if song.is_favorite %}
                is favorite
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"

{% if all_albums %}
    <h1>Here are my albums:</h1>
    <ul>
        {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% endif %}